name: My Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty artifact
        run: |
          touch empty.txt
        # Add empty.txt to artifacts
        # Note: '**/*' includes all files and directories
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: empty
          path: empty.txt
      - name: Upload to Dropbox
        uses: andyjessop/dropbox-upload@v2
        with:
          ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          REMOTE_PATH: /test-results
          LOCAL_PATH: empty.txt
