name: My Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty artifact
        run: |
          touch empty.txt
        # Add empty.txt to artifacts
        # Note: '**/*' includes all files and directories
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: empty
          path: empty.txt
      - name: Deploy to Dropbox
        uses: aTable/deploy-to-dropbox@v1.0.7
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          GLOB: empty.txt
          DROPBOX_DESTINATION_PATH_PREFIX: /

